config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
  get 'calendar/callback'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'lists#index'
resources :genres
resources :lists
get "genre_search/:id", to: "lists#genre_search",as: 'genre_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :lists
  validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :genre

    validates :name, presence: true
    validates :rate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    flash[:notice] = "ジャンルを追加しました"
    redirect_to genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "変更を保存しました"
    redirect_to genres_path
  end
  
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path 
  end

  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all.order(rate: :DESC)
    @list = List.new
    @genres = Genre.all
    
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
      flash[:notice] = "投稿に成功しました"
    else
      @lists = List.all
      @genres = Genre.all
      render "index"
    end
  end

  def show
    @list = List.find(params[:id])
  end
  
  def edit
    @list = List.find(params[:id])
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path(@list)
    else
      render "edit"
    end
  end
  
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end
  
  def genre_search
    #ジャンル検索欄表示用にジャンルを全て取得
    @genres = Genre.all
    #受け取ったジャンルIDと同じジャンルをリストから探し取得
    @genre_searched = Genre.find(params[:id])
    #ジャンルが上のgenre_searchと一致する商品のみを（全て）取得
    @all_items_searched = List.where(genre_id: @genre_searched.id).order(rate: :DESC)
    #直前で受け取った商品の中から,ページネーションのために8個まで取得
    @items = @all_items_searched
  end

  private
  def list_params
    params.require(:list).permit(:name, :body, :rate,:genre_id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/genres/edit.html.erb
<div class="container">
  <div class="row mt-5">
     <h3 class = "admin-customers-index" style="background-color:rgba(107,90,105,0.1);">ジャンル編集</h3>
  </div>
  <div class = "row m-5">
    <%= form_with model:@genre, local:true do |f| %>
      <div class="form-group form-inline">
      <label for="genre_name">ジャンル名</label>
        <%= f.text_field :name, class: "form-control mx-5" %>
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container">

  <div class="row mt-5">
      <p class="text-success"><%= flash[:notice]%></p>
      <h3 class = "admin-customers-index" style="background-color:rgba(107,90,105,0.1);">ジャンル一覧・追加</h3>
    </div>  
    <div class = "row m-5">
      <%= form_with model:@genre, url:genres_path,local:true do |f| %>
      <div class="form-group form-inline">
      <label for="genre_name">ジャンル名</label>
        <%= f.text_field :name, class: "form-control mx-5" %>
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>

  <div class="container">
      <div class="row-md-5 mt-5">
        <div class="col-4">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td>
                <%= link_to "編集する", edit_genre_path(genre), class: "btn btn-sm btn-success" %>
                <%= link_to "削除する", genre_path(genre),method: :delete, class: "btn btn-sm btn-danger ml-2" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to ">>>>リスト一覧へ", lists_path, class: "d-block mt-4 mb-5" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer style="background-color:#1b1733;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <form name="timer">
        <input type="text" value="" class="mt-5 mr-3"><p class="text-white d-inline-block">分</p>
        <input type="text" value=""><p class="text-white d-inline-block">秒</p><br>
        <input type="button" value="スタート" onclick="cntStart()" class="mt-3 mr-3">
        <input type="button" value="ストップ" onclick="cntStop()" class="mb-5">
        </form>
      </div>
    </div>
  </div>
</footer>

<script>

var timer1; //タイマーを格納する変数（タイマーID）の宣言


//カウントダウン関数を1000ミリ秒毎に呼び出す関数
function cntStart()
{
  document.timer.elements[2].disabled=true;
  timer1=setInterval("countDown()",1000);
}

//タイマー停止関数
function cntStop()
{
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}

//カウントダウン関数
function countDown()
{
  var min=document.timer.elements[0].value;
  var sec=document.timer.elements[1].value;
  
  if( (min=="") && (sec=="") )
  {
    alert("時刻を設定してください！");
    reSet();
  }
  else
  {
    if (min=="") min=0;
    min=parseInt(min);
    
    if (sec=="") sec=0;
    sec=parseInt(sec);
    
    tmWrite(min*60+sec-1);
  }
}

//残り時間を書き出す関数
function tmWrite(int)
{
  int=parseInt(int);
  
  if (int<=0)
  {
    reSet();
    alert("時間です！");
  }
  else
  {
    //残り分数はintを60で割って切り捨てる
    document.timer.elements[0].value=Math.floor(int/60);
    //残り秒数はintを60で割った余り
    document.timer.elements[1].value=int % 60;
  }
}

//フォームを初期状態に戻す（リセット）関数
function reSet()
{
  document.timer.elements[0].value="0";
  document.timer.elements[1].value="0";
  document.timer.elements[2].disabled=false;
  clearInterval(timer1);
}  
  
</script>

app/views/layouts/_genre_search.html.erb
<table class="table text-center">
    <thead>
      <tr class="table-warning">
        <th>ジャンル</th>
      </tr>
    </thead>
    <tbody>
      <% genres.each do |genre| %>
      <tr>
        <td><h5><%= link_to genre.name, genre_search_path(genre),class: 'font-weight-bold'%></h5></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/layouts/_header.html.erb
<header class="shadow-sm" style="background-color:#800040;">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3 text-white" href="/">サクサクタスク</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer'  %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
    <p class="text-success"><%= flash[:notice]%></p>
    <div class=""><h3 style="background-color:rgba(107,90,105,0.1);">編集</h3></div>
    
    <div class ="mx-auto row-md-12">
        <%= form_with model:@list, url:list_path(@list),local:true do |f| %>
        <div class="col-md-5">
                        <label for="name" class="mt-5">タイトル</label>
                        <%= f.text_field :name, class: "form-control mx-5" %>
                        <label for="body" class="mt-5">説明</label>
                        <%= f.text_area :body, class: "form-control mx-5" %>
        </div>
        <div class="col-md-5">
                        <label class="mt-5">ジャンル</label>
                           <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class:"form-control" %>
                         <div class="mt-5" id="star">
                           <%= f.label :rate,'評価 :', class:"1" %>
                           <%= f.hidden_field :rate, id: :review_star %>
                         </div>
                         <script>
                         $('#star').raty({
                           size     : 36,
                           starOff:  '<%= asset_path('star-off.png') %>',
                           starOn : '<%= asset_path('star-on.png') %>',
                           starHalf: '<%= asset_path('star-half.png') %>',
                           scoreName: 'list[rate]',
                           half: true,
                         });
                         </script>
                         <%= f.submit '新規登録', class: "btn btn-success mt-5" %>
       </div>
      <% end %>
    </div>
</div>

app/views/lists/genre_search.html.erb
<div class = "container">
  <div class = "row  pt-3">
    <!--ジャンル検索欄-->
    <div class="col-md-3">
      <%= render 'layouts/genre_search', genres: @genres %>
      <!--すべての一覧へのリンク-->
      <%= link_to ">>>>Todo一覧へ", lists_path, class: "d-block mt-4" %>
    </div>
    <!--一覧-->
    <div class = "col-md-9">
      <h3 class = "m-2 py-2" style = 'background: linear-gradient(to right, #fff 0%, #ffd6ff 30%, #ffd6ff 70%, #fff 100%);  font-weight: 600; width: 100%;' >
        <%= @genre_searched.name %>一覧<span class = "h5">（<%= "#{@all_items_searched.count}件" %>）</span>
      </h3>
      <!--いじる-->
      <div>
      <table class="table table-striped">
        <tbody>
        
                <% if !(@items.blank?) %>
                        <% @items.each do |item| %>
                        <tr>
                                <td><%= link_to list_path(item) do %><h4 class="font-weight-bold"><%= item.name %></h4><% end %></td>
                                <td>
                                  <%= link_to list_path(item.id) do %>
                                  <div>
                                  <div id="star-rate-<%= item.id %>"></div>
                                  <script>
                                   $('#star-rate-<%= item.id %>').raty({
                                     size: 36,
                                     starOff:  '<%= asset_path('star-off.png') %>',
                                     starOn : '<%= asset_path('star-on.png') %>',
                                     starHalf: '<%= asset_path('star-half.png') %>',
                                     half: true,
                                     readOnly: true,
                                     score: <%= item.rate %>,
                                   });
                                   </script>
                                   </div>
                                   <% end %>
                            </td>
                        </tr>
                        <% end %>
                <% end %>
        </tbody>
      </table>
      </div>
      <!--いじる-->
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
    <p class="text-success"><%= flash[:notice]%></p>
    <%= link_to 'カレンダー',calendar_callback_path %>
    <div class=""><h3 style="background-color:rgba(107,90,105,0.1);">投稿</h3></div>

    <div class="row-md-12">
        <%= form_with model:@list, url:lists_path,local:true do |f| %>
        <div class="col-md-6 mb-3">
            <div class="">
                <label class="control-label">タイトル</label>
                <%= f.text_field :name,class: "form-control mx-5 border-secondary"%>
            </div>
            <label for="body">説明</label>
            <%= f.text_area :body, class: "form-control mx-5 border-secondary" %>
        </div>
        <div class="col-md-6">
            <label class="mt-3 mb-4">ジャンル</label>
               <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class:"form-control" %>
             <div class="mb-3" id="star">
               <%= f.label :rate,'評価 :', class: "1" %>
               <%= f.hidden_field :rate, id: :review_star %>
             </div>
             <script>
             $('#star').raty({
               size     : 36,
               starOff:  '<%= asset_path('star-off.png') %>',
               starOn : '<%= asset_path('star-on.png') %>',
               starHalf: '<%= asset_path('star-half.png') %>',
               scoreName: 'list[rate]',
               half: true,
             });
             </script>
             <%= f.submit '新規登録', class: "btn btn-success mt-3 w-25" %>
        </div>
      <% end %>
    </div>
    
    
    <div class="row mt-5">
        
        <div class="col-md-3">
            <%= render 'layouts/genre_search', genres: @genres %>
            <%= link_to ">>>>ジャンルを追加する", genres_path, class: "d-block mt-4" %>
        </div>
        
        <div class="col-md-9">
            <table class="table table-striped">
              <tbody>
                <% @lists.each do |list| %>
                <tr>
                　<td><%= link_to list_path(list.id) do %> <h4 class="font-weight-bold"><%= list.name %></h4><% end %></td>
                  <td>
                    <%= link_to list_path(list.id) do %>
                    <div class="">
                        <div id="star-rate-<%= list.id %>"></div>
                        <script>
                        $('#star-rate-<%= list.id %>').raty({
                           size: 36,
                           starOff:  '<%= asset_path('star-off.png') %>',
                           starOn : '<%= asset_path('star-on.png') %>',
                           starHalf: '<%= asset_path('star-half.png') %>',
                           half: true,
                           readOnly: true,
                           score: <%= list.rate %>,
                        });
                        </script>
                   </div>
                   <% end %>
                   </td>
                  <td>
                    <%= link_to "編集する", edit_list_path(list), class: "btn btn-sm btn-success ml-3" %>
                    <%= link_to "削除する", list_path(list),method: :delete, class: "btn btn-sm btn-danger ml-3" %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
        </div>
    </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-12">
      
      <div class="mb-5" >
        <h4 style="background-color:rgba(107,90,105,0.1);">タイトル</h4>
        <%= @list.name %>
      </div>
      
      <div class="mb-5">
        <h4 style="background-color:rgba(107,90,105,0.1);">説明</h4>
        <%= @list.body %>
      </div>
      
      <div class="mb-5">
        <h4 style="background-color:rgba(107,90,105,0.1);">ジャンル</h4>
        <%= @list.genre.name %>
      </div>
    
      <div class="mb-5">
        <div id="star-rate-<%= @list.id %>"></div>
          <script>
          $('#star-rate-<%= @list.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @list.rate %>,
          });
          </script>
        <div class="">
        <%= @list.rate %>
        </div>
      </div>
    <%= link_to "編集する", edit_list_path(@list), class: "btn btn-sm btn-success w-25" %>
    <%= link_to "削除する", list_path(@list),method: :delete, class: "btn btn-sm btn-danger ml-5 w-25" %>
    </div>
  </div>
  <%= link_to "一覧へ",lists_path ,class: "mt-5" %>
</div>